In [ ]:
#loading data
import pandas as pd
df = pd.read_csv('aug_test.csv')

In [ ]:
df.shape

(2129, 13)

In [ ]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

In [ ]:
# label encoding --> gender
from sklearn.preprocessing import LabelEncoder
df_encoded = df.copy()
label_encoder = LabelEncoder()
df_encoded['gender'] = label_encoder.fit_transform(df_encoded['gender'])
df_encoded

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,32403,city_41,0.827,1,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21
1,9858,city_103,0.920,0,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
2,31806,city_21,0.624,1,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
3,27385,city_13,0.827,1,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
4,27724,city_103,0.920,1,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,1,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2125,195,city_136,0.897,1,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2126,31762,city_100,0.887,1,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2127,7873,city_102,0.804,1,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2128,12215,city_102,0.804,1,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

In [ ]:
# label encoding --> relevent_experience
from sklearn.preprocessing import LabelEncoder
df_encoded = df.copy()
label_encoder = LabelEncoder()
df_encoded['relevent_experience'] = label_encoder.fit_transform(df_encoded['relevent_experience'])
df_encoded

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,32403,city_41,0.827,Male,0,Full time course,Graduate,STEM,9,<10,NaN,1,21
1,9858,city_103,0.920,Female,0,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
2,31806,city_21,0.624,Male,1,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
3,27385,city_13,0.827,Male,0,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
4,27724,city_103,0.920,Male,0,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,1,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2125,195,city_136,0.897,Male,0,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2126,31762,city_100,0.887,Male,1,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2127,7873,city_102,0.804,Male,0,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2128,12215,city_102,0.804,Male,0,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

In [ ]:
df_encoded['gender_encoded'] = label_encoder.fit_transform(df_encoded['gender'])
df_encoded['relevent_experience_encoded'] = label_encoder.fit_transform(df_encoded['relevent_experience'])
df_encoded['enrolled_university_encoded'] = label_encoder.fit_transform(df_encoded['enrolled_university'])
df_encoded

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,gender_encoded,relevent_experience_encoded,enrolled_university_encoded
0,32403,city_41,0.827,Male,0,Full time course,Graduate,STEM,9,<10,NaN,1,21,1,0,0
1,9858,city_103,0.920,Female,0,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98,0,0,2
2,31806,city_21,0.624,Male,1,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15,1,1,2
3,27385,city_13,0.827,Male,0,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39,1,0,2
4,27724,city_103,0.920,Male,0,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,1,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15,1,1,2
2125,195,city_136,0.897,Male,0,no_enrollment,Masters,STEM,18,NaN,NaN,2,30,1,0,2
2126,31762,city_100,0.887,Male,1,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18,1,1,2
2127,7873,city_102,0.804,Male,0,Full time course,High School,NaN,7,100-500,Public Sector,1,84,1,0,0
2128,12215,city_102,0.804,Male,0,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11,1,0,2

In [ ]:
# label encoding with order
education_level_encoded_dict = {"Primary School	":0, "High School":1, "Graduate":2, "Masters":3 }
df_encoded["education_level_encoded"] = df_encoded["education_level"].map(education_level_encoded_dict)
df_encoded

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,gender_encoded,relevent_experience_encoded,enrolled_university_encoded,education_level_encoded
0,32403,city_41,0.827,Male,0,Full time course,Graduate,STEM,9,<10,NaN,1,21,1,0,0,2.0
1,9858,city_103,0.920,Female,0,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98,0,0,2,2.0
2,31806,city_21,0.624,Male,1,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15,1,1,2,1.0
3,27385,city_13,0.827,Male,0,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39,1,0,2,3.0
4,27724,city_103,0.920,Male,0,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72,1,0,2,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,1,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15,1,1,2,2.0
2125,195,city_136,0.897,Male,0,no_enrollment,Masters,STEM,18,NaN,NaN,2,30,1,0,2,3.0
2126,31762,city_100,0.887,Male,1,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18,1,1,2,NaN
2127,7873,city_102,0.804,Male,0,Full time course,High School,NaN,7,100-500,Public Sector,1,84,1,0,0,1.0
2128,12215,city_102,0.804,Male,0,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11,1,0,2,3.0

In [ ]:
# one hot encoding -> city
df_encoded = pd.get_dummies(df_encoded, columns=['city'], prefix='city')
df_encoded

,enrollee_id,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,...,city_city_84,city_city_89,city_city_9,city_city_90,city_city_91,city_city_93,city_city_94,city_city_97,city_city_98,city_city_99
0,32403,0.827,Male,0,Full time course,Graduate,STEM,9,<10,NaN,...,False,False,False,False,False,False,False,False,False,False
1,9858,0.920,Female,0,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,...,False,False,False,False,False,False,False,False,False,False
2,31806,0.624,Male,1,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,...,False,False,False,False,False,False,False,False,False,False
3,27385,0.827,Male,0,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,...,False,False,False,False,False,False,False,False,False,False
4,27724,0.920,Male,0,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,0.920,Male,1,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,...,False,False,False,False,False,False,False,False,False,False
2125,195,0.897,Male,0,no_enrollment,Masters,STEM,18,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
2126,31762,0.887,Male,1,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,...,False,False,False,False,False,False,False,False,False,False
2127,7873,0.804,Male,0,Full time course,High School,NaN,7,100-500,Public Sector,...,False,False,False,False,False,False,False,False,False,False
2128,12215,0.804,Male,0,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df_encoded = pd.get_dummies(df_encoded, columns=["major_discipline"], prefix="major_discipline")
df_encoded

,enrollee_id,city_development_index,gender,relevent_experience,enrolled_university,education_level,experience,company_size,company_type,last_new_job,...,city_city_94,city_city_97,city_city_98,city_city_99,major_discipline_Arts,major_discipline_Business Degree,major_discipline_Humanities,major_discipline_No Major,major_discipline_Other,major_discipline_STEM
0,32403,0.827,Male,0,Full time course,Graduate,9,<10,NaN,1,...,False,False,False,False,False,False,False,False,False,True
1,9858,0.920,Female,0,no_enrollment,Graduate,5,NaN,Pvt Ltd,1,...,False,False,False,False,False,False,False,False,False,True
2,31806,0.624,Male,1,no_enrollment,High School,<1,NaN,Pvt Ltd,never,...,False,False,False,False,False,False,False,False,False,False
3,27385,0.827,Male,0,no_enrollment,Masters,11,10/49,Pvt Ltd,1,...,False,False,False,False,False,False,False,False,False,True
4,27724,0.920,Male,0,no_enrollment,Graduate,>20,10000+,Pvt Ltd,>4,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,0.920,Male,1,no_enrollment,Graduate,16,NaN,Public Sector,4,...,False,False,False,False,False,False,True,False,False,False
2125,195,0.897,Male,0,no_enrollment,Masters,18,NaN,NaN,2,...,False,False,False,False,False,False,False,False,False,True
2126,31762,0.887,Male,1,no_enrollment,Primary School,3,NaN,Pvt Ltd,never,...,False,False,False,False,False,False,False,False,False,False
2127,7873,0.804,Male,0,Full time course,High School,7,100-500,Public Sector,1,...,False,False,False,False,False,False,False,False,False,False
2128,12215,0.804,Male,0,no_enrollment,Masters,15,10000+,Pvt Ltd,2,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
# onr hot encoding -> gender
df_encoded = pd.get_dummies(df_encoded, columns=["gender"], prefix="gender")
df_encoded

,enrollee_id,city_development_index,relevent_experience,enrolled_university,education_level,experience,company_size,company_type,last_new_job,training_hours,...,city_city_99,major_discipline_Arts,major_discipline_Business Degree,major_discipline_Humanities,major_discipline_No Major,major_discipline_Other,major_discipline_STEM,gender_Female,gender_Male,gender_Other
0,32403,0.827,0,Full time course,Graduate,9,<10,NaN,1,21,...,False,False,False,False,False,False,True,False,True,False
1,9858,0.920,0,no_enrollment,Graduate,5,NaN,Pvt Ltd,1,98,...,False,False,False,False,False,False,True,True,False,False
2,31806,0.624,1,no_enrollment,High School,<1,NaN,Pvt Ltd,never,15,...,False,False,False,False,False,False,False,False,True,False
3,27385,0.827,0,no_enrollment,Masters,11,10/49,Pvt Ltd,1,39,...,False,False,False,False,False,False,True,False,True,False
4,27724,0.920,0,no_enrollment,Graduate,>20,10000+,Pvt Ltd,>4,72,...,False,False,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,0.920,1,no_enrollment,Graduate,16,NaN,Public Sector,4,15,...,False,False,False,True,False,False,False,False,True,False
2125,195,0.897,0,no_enrollment,Masters,18,NaN,NaN,2,30,...,False,False,False,False,False,False,True,False,True,False
2126,31762,0.887,1,no_enrollment,Primary School,3,NaN,Pvt Ltd,never,18,...,False,False,False,False,False,False,False,False,True,False
2127,7873,0.804,0,Full time course,High School,7,100-500,Public Sector,1,84,...,False,False,False,False,False,False,False,False,True,False
2128,12215,0.804,0,no_enrollment,Masters,15,10000+,Pvt Ltd,2,11,...,False,False,False,False,False,False,True,False,True,False

In [ ]:
# frequency encoding --> city
from sklearn.preprocessing import LabelEncoder
df_encoded = df.copy()
city_freq = df_encoded["city"].value_counts().to_dict()
df_encoded["city_count_encoded"] = df_encoded["city"].map(city_freq)
df_encoded

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,city_count_encoded
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21,9
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98,473
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15,318
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39,10
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72,473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15,473
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30,60
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18,21
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84,30
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11,30

In [ ]:
unique_city = df_encoded["city"].unique()
unique_city

array(['city_41', 'city_103', 'city_21', 'city_13', 'city_23', 'city_160',
       'city_173', 'city_90', 'city_46', 'city_98', 'city_118',
       'city_114', 'city_134', 'city_73', 'city_116', 'city_16',
       'city_165', 'city_61', 'city_136', 'city_45', 'city_104',
       'city_28', 'city_149', 'city_105', 'city_76', 'city_83', 'city_97',
       'city_64', 'city_31', 'city_19', 'city_11', 'city_143', 'city_100',
       'city_67', 'city_75', 'city_127', 'city_101', 'city_139',
       'city_27', 'city_71', 'city_99', 'city_70', 'city_69', 'city_44',
       'city_150', 'city_74', 'city_176', 'city_155', 'city_167',
       'city_30', 'city_89', 'city_57', 'city_162', 'city_36', 'city_107',
       'city_128', 'city_39', 'city_102', 'city_65', 'city_10', 'city_40',
       'city_152', 'city_123', 'city_179', 'city_50', 'city_115',
       'city_77', 'city_159', 'city_80', 'city_72', 'city_171',
       'city_158', 'city_138', 'city_142', 'city_25', 'city_14',
       'city_33', 'city_79', 'city_91', 'city_53', 'city_175', 'city_9',
       'city_26', 'city_1', 'city_54', 'city_24', 'city_48', 'city_126',
       'city_82', 'city_141', 'city_43', 'city_106', 'city_133',
       'city_93', 'city_121', 'city_2', 'city_37', 'city_20', 'city_94',
       'city_12', 'city_42', 'city_117', 'city_144', 'city_157',
       'city_145', 'city_180', 'city_84', 'city_78'], dtype=object)

In [ ]:
# label encoding --> gender
from sklearn.preprocessing import LabelEncoder
df_encoded = df.copy()
label_encoder = LabelEncoder()
df_encoded['gender_encoded'] = label_encoder.fit_transform(df_encoded['gender'])
df_encoded

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,gender_encoded
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21,1
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98,0
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15,1
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39,1
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15,1
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30,1
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18,1
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84,1
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11,1

In [ ]:
# target encoding of education (feature) and target is grnder(it's avg we have to calculate)
gender_target_mean = df_encoded.groupby("education_level")["gender_encoded"].mean()
gender_target_mean

education_level
Graduate          1.392435
High School       1.477477
Masters           1.405242
Phd               1.277778
Primary School    1.777778
Name: gender_encoded, dtype: float64

In [ ]:
# target encoding of education (feature) and target is grnder(it's avg we have to calculate)
gender_target_mean = df_encoded.groupby("education_level")["gender_encoded"].mean().to_dict()
df_encoded["gender_target_education_encoded"] = df_encoded["education_level"].map(gender_target_mean)
df_encoded

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,gender_encoded,education_level_encoded,gender_target_encoded,education_target_encoded,gender_target_education_encoded
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21,1,2.0,1.392435,2.143478,1.392435
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98,0,2.0,1.392435,2.155039,1.392435
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15,1,1.0,1.477477,2.143478,1.477477
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39,1,3.0,1.405242,2.143478,1.405242
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72,1,2.0,1.392435,2.143478,1.392435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15,1,2.0,1.392435,2.143478,1.392435
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30,1,3.0,1.405242,2.143478,1.405242
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18,1,NaN,1.777778,2.143478,1.777778
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84,1,1.0,1.477477,2.143478,1.477477
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11,1,3.0,1.405242,2.143478,1.405242

In [ ]:
# label encoding with order
education_level_encoded_dict = {"Primary School	":0, "High School":1, "Graduate":2, "Masters":3 }
df_encoded["education_level_encoded"] = df_encoded["education_level"].map(education_level_encoded_dict)
df_encoded

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,gender_encoded,education_level_encoded
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21,1,2.0
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98,0,2.0
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15,1,1.0
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39,1,3.0
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72,1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15,1,2.0
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30,1,3.0
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18,1,NaN
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84,1,1.0
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11,1,3.0

In [ ]:
# target education , feature gender
education_target_mean = df_encoded.groupby("gender")["education_level_encoded"].mean()
education_target_mean

gender
Female    2.155039
Male      2.143478
Other     1.863636
Name: education_level_encoded, dtype: float64

In [ ]:
# target education , feature gender
education_target_mean = df_encoded.groupby("gender")["education_level_encoded"].mean()
df_encoded["education_target_gender_encoded"] = df_encoded["gender"].map(education_target_mean)
df_encoded

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,gender_encoded,education_level_encoded,gender_target_encoded,education_target_encoded,gender_target_education_encoded,education_target_gender_encoded
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21,1,2.0,1.392435,2.143478,1.392435,2.143478
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98,0,2.0,1.392435,2.155039,1.392435,2.155039
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15,1,1.0,1.477477,2.143478,1.477477,2.143478
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39,1,3.0,1.405242,2.143478,1.405242,2.143478
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72,1,2.0,1.392435,2.143478,1.392435,2.143478
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15,1,2.0,1.392435,2.143478,1.392435,2.143478
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30,1,3.0,1.405242,2.143478,1.405242,2.143478
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18,1,NaN,1.777778,2.143478,1.777778,2.143478
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84,1,1.0,1.477477,2.143478,1.477477,2.143478
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11,1,3.0,1.405242,2.143478,1.405242,2.143478